apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts # same as the template > metadata > labels > app. We are trying to the service to find all the pods having this label think of the label and selector system as css classes. The selector selects the label
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # port of the node service
      targetPort: 4000 # port of the container
